INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (1, 'Rektorat', 'A-0', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 1, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (2, 'Wydział Wiertnictwa, Nafty i Gazu', 'A-1', 'Władysława Reymonta 8, 33-332 Kraków', null, 4, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (3, 'Wydział Metali Nieżelaznych', 'A-2', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 5, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (4, 'Centrum Międzynarodowej Promocji Technologi i Edukacji AGH - UNESCO', 'A-3', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 6, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (5, 'Wydział Inżynierii Lądowej i Gospodarki Zasobami', 'A-4', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 7, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (6, 'Wydział Elektrotechniki, Automatyki, Informatyki i Inżynierii Biomedycznej', 'B-1', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 9, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (7, 'Wydział Inżynierii Mechanicznej i Robotyki', 'B-2', 'aleja Adama Mickiewicza 30/2, 30-059 Kraków', null, 13, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (8, 'AGH B3', 'B-3', 'aleja Adama Mickiewicza 30/3, 30-059 Kraków', null, 14, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (9, 'Wydział Inżynierii Metali i Informatyki Przemysłowej', 'B-4', 'aleja Adama Mickiewicza 30/4, 30-059 Kraków', null, 17, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (10, 'Wydział Inżynierii Metali i Informatyki Przemysłowej', 'B-5', 'Czarnowiejska 66, 30-059 Kraków', null, 19, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (11, 'AGH B6', 'B-6', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 22, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (12, 'Wydział Matematyki Stosowanej', 'B-7', 'Czarnowiejska 70, 30-054 Kraków', null, 23, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (13, 'Wydział Inżynierii Materiałowej i Ceramiki ', 'B-8', 'aleja Adama Mickiewicza 30/0.24, 30-059 Kraków', null, 25, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (14, 'AGH Teleinformatyka', 'B-9', 'Czarnowiejska 74, 30-054 Kraków', null, 30, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (15, 'Biblioteka Główna Akademii Górniczo-Hutniczej', 'U-1', 'aleja Adama Mickiewicza 30, 30-059 Kraków', '', 64, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (16, 'Centrum Rozwiązań Informatycznych AGH', 'C-1', 'aleja Adama Mickiewicza 30/C1, 30-059 Kraków', null, 32, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (17, 'Centrum Obsługi Projektów', 'C-2', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 34, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (18, 'Katedra Informatyki Stosowanej, AGH', 'C-3', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 35, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (19, 'Wydział Geodezji Górniczej i Inżynierii Środowiska', 'C-4', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 37, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (20, 'Centrum Energetyki AGH', 'C-5', 'Czarnowiejska 36, 30-054 Kraków', null, 39, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (21, 'AGH C6', 'C-6', 'Czarnowiejska 32A, 33-332 Kraków', null, 40, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (22, 'Wydział Humanistyczny', 'C-7', 'Czarnowiejska 36/Budynek C-7, 30-054 Kraków', null, 41, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (23, 'AGH D2', 'D-2', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 43, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (24, 'Wydział Energetyki i Paliw', 'D-4', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 45, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (25, 'Katedra Telekomunikacji', 'D-5', 'Czarnowiejska 78, 30-054 Kraków', null, 47, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (26, 'AGH D7', 'D-7', 'Władysława Reymonta 21b, 30-059 Kraków', null, 49, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (27, 'Wydział Fizyki i Informatyki Stosowanej', 'D-10', 'Władysława Reymonta 19, 30-059 Kraków', null, 52, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (28, 'AGH D11', 'D-11', 'Kawiory 26a, 33-332 Kraków', null, 55, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (29, 'Wydział Informatyki, Elektroniki i Telekomunikacji', 'D-17', 'Kawiory 21, 30-055 Kraków', null, 56, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (30, 'Katedra Energetyki Wodorowej - Wydział Energetyki i Paliw', 'H-B3B4', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 59, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (31, 'AGH H-B6', 'H-B6', 'aleja Adama Mickiewicza 30, 30-059 Kraków', null, 60, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (32, 'Uczelniana Rada Samorządu Studentów', 'S-1', 'Władysława Reymonta 13A, 30-059 Kraków', null, 62, 0);
INSERT INTO places (id, name, code, address, description, main_image_id, creator_id) VALUES (33, 'Przychodnia Akademicka', 'U-3', 'Akademicka 5, 33-332 Kraków', null, 66, 0);
